services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
       - db-data:/var/lib/postgresql/data/pgdata  # named volume
    restart: unless-stopped
    healthcheck: # Health check para asegurarnos que la bd esté completamente levantada
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  web:
    image: odoo:18
    depends_on:
      db:
        condition: service_healthy # Solo levantamos el servidor web si la base de datos esta healthy
    ports:
      - "0.0.0.0:8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons          # bind mount (necesario para desarrollo de modulos)
      - ./odoo.conf:/etc/odoo/odoo.conf     # bind mount para sobrrescribir config
      - odoo-data:/var/lib/odoo             # named volume
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: unless-stopped

volumes:          
  db-data:
  odoo-data: