[options]
data_dir = /var/lib/odoo

addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

admin_passwd = admin123

workers = 0
proxy_mode = False

web.base.url = http://localhost:8069
web.base.url.freeze = True